services:
  webserver:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./django_rest_api.conf:/etc/nginx/conf.d/default.conf
      - ./static:/var/www/static
      - ./docs:/var/www/docs
  python:
    image: "python:3.13-alpine"
    volumes:
      - .:/app
    working_dir: /app
    command: "tail -f /dev/null"
    env_file: ".env"
    expose:
      - 8000
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
