# Generated by Django 5.1.5 on 2025-02-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_shoppingcart_shoppingcartposition_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.shoppingcart'),
        ),
    ]
