# Generated by Django 5.1.5 on 2025-02-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_shoppingcartposition_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartposition',
            name='product',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
