# Generated by Django 5.1.5 on 2025-02-03 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_shoppingcartposition_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartposition',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
